[package]
edition = "2021"
name    = "l2o_indexer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix              = "0.13.1"
actix-cors         = "0.6.4"
actix-web          = "4.4.0"
actix-web-actors   = "4.2.0"
anyhow             = "1.0.75"
async-channel      = "2.2.0"
bitcoincore-rpc    = "0.18.0"
futures            = "0.3.28"
indexer-sdk        = { git = "https://github.com/GopherJ/indexer-sdk", branch = "main" }
once_cell          = "1.18.0"
serde              = { version = "1.0.188", features = ["derive"] }
serde_json         = "1.0.107"
thiserror          = "1.0.49"
tokio              = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tracing            = "0.1.40"
tracing-log        = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
